### ISSUE TITLE
Is there a limitation in bit rate or any other type of constraint on the wav file?

### ISSUE THREAD

**Issue by jcopps** [bastibe/pocoder#1]
I tried to get this file processed. But it throws N number of errors. 
Can you please help/fix them. 
https://ufile.io/s2vkw

**Comment by bastibe** [comment]
Please show me the exact code you are trying to run, the error message you get, and tell me the version of Python or Matlab you are running.

**Comment by jcopps** [comment]
Traceback (most recent call last):
  File "pocoder.py", line 123, in <module>
    out = vocode(data, fs, block_len, overlap, order)
  File "pocoder.py", line 79, in vocode
    block *= hann(len(block)) * gain_correction
ValueError: non-broadcastable output operand with shape (353,1) doesn't match the broadcast shape (353,353)

Also had to fix this line: 
samples = data[int(idx*shift_samples):int(idx*shift_samples+block_samples)]

PYTHON: 2.7.10

**Comment by bastibe** [comment]
Try a one-dimensional array instead of a mono array.

**Comment by jcopps** [comment]
Its a blackbox to me. 
The file that was given as input is available in the issue description.

**Comment by bastibe** [comment]
You treat me as if I am a customer service representative paid for helping you. I am not. I do this in my free time, out of kindness. I am not obligated to help you.

The example code you gave me is not sufficient. I do not know what your `data` is, or your `fs`, or your `block_len`, etc. From the error message, which is incomplete as well, I can tell you that the shape of your data is incorrect, and I think you should try some one-dimensional data instead of your two-dimensional mono array.

Now either you try to help me help you, or you are on your own.

**Comment by jcopps** [comment]
I am sorry I didn't mean to be rude. Sorry if thats how I sounded in the above text. 
See, I am new to vocoders and am just trying to run some sample codes and came across this one which was quite straight forward to use it. 
Didn't know the data or got to know that the data has to be in a particular form. 
#Cheers

**Comment by jcopps** [comment]
Apologies. That wasn't intentional. 
I am all new to vocoders, and hence I was just trying to find the most straight forward apps to understand its purpose.
